import type { FighterDefinition } from '../types'

/**
 * fighter-1 «Разработчик» — source: figther-1/Разработчик.png
 *
 * Atlas rows (see tools/slice_sprites.py, row 0 = portraits):
 *  1 idle (0-1) + hit reaction (2-5)   7 lightning beam special
 *  2 walk                               8 code pillar (char 0-3,5,7 + pillar vfx 4,6,8)
 *  3 jab                                9 victory
 *  4 kick                              10 dizzy
 *  5 jump                              11 KO
 *  6 portal (intro)
 */
const developer: FighterDefinition = {
  id: 'developer',
  name: 'Разработчик',
  profile: {
    archetype: 'Душный вайбкодер',
    speed: 'Выше высокой',
    health: 'Средние',
  },
  assetDir: 'developer',
  portraits: { normal: 0, hurt: 3, ko: 4, select: 0 },
  spriteScale: 1.05,
  stats: {
    maxHp: 1400,
    walkSpeed: 6.2,
    backWalkSpeed: 5,
    jumpVelocity: 24,
    jumpForwardSpeed: 7.5,
    weight: 1,
  },
  hurtboxes: {
    standing: [
      { x: 0, y: 0, width: 140, height: 250 },
      { x: 0, y: 250, width: 160, height: 150 },
    ],
    airborne: [{ x: 0, y: 30, width: 150, height: 330 }],
    down: [{ x: 0, y: 0, width: 300, height: 90 }],
  },
  animations: {
    idle: { row: 1, frames: [0, 1], ticksPerFrame: 22, loop: true },
    walk: { row: 2, frames: [0, 1, 2, 3], ticksPerFrame: 7, loop: true },
    jumpSquat: { row: 5, frames: [0], ticksPerFrame: 4, loop: false },
    jump: { row: 5, frames: [1], ticksPerFrame: 6, loop: false },
    fall: { row: 5, frames: [2], ticksPerFrame: 6, loop: false },
    land: { row: 5, frames: [3], ticksPerFrame: 5, loop: false },
    hit: { row: 1, frames: [3, 3, 4], ticksPerFrame: 5, loop: false },
    block: { row: 8, frames: [7], ticksPerFrame: 10, loop: false },
    stun: { row: 10, frames: [1, 2, 3], ticksPerFrame: 9, loop: true },
    ko: { row: 11, frames: [1, 2, 3, 4], ticksPerFrame: 8, loop: false },
    win: { row: 9, frames: [1, 2, 3, 4, 5, 6], ticksPerFrame: 9, loop: false },
    intro: {
      row: 6,
      frames: [3, 4, 5, 6, 7, 8],
      ticksPerFrame: 12,
      loop: false,
      effect: { style: 'portal', splitX: 0, originY: 190, color: '#5ad8ff' },
    },
  },
  attacks: {
    light: {
      id: 'dev-jab',
      name: 'Джеб',
      kind: 'light',
      damage: 40,
      startupFrames: 5,
      activeFrames: 3,
      recoveryFrames: 10,
      hitbox: { x: 135, y: 250, width: 120, height: 70 },
      knockback: { horizontalForce: 3, verticalForce: 0, duration: 15 },
      blockInteraction: 'blockable',
      blockstun: 11,
      hitstop: 5,
      cancelInto: ['light', 'kick', 'heavy', 'special'],
      lunge: 1.5,
      impact: 'light',
      sound: 'whiff-light',
      hitSound: 'hit-light',
      animation: { row: 3, startup: [1], active: [2], recovery: [2, 0] },
    },
    kick: {
      id: 'dev-kick',
      name: 'Удар ногой',
      kind: 'kick',
      damage: 65,
      startupFrames: 8,
      activeFrames: 4,
      recoveryFrames: 15,
      hitbox: { x: 150, y: 90, width: 170, height: 110 },
      knockback: { horizontalForce: 5.5, verticalForce: 0, duration: 19 },
      blockInteraction: 'blockable',
      blockstun: 14,
      hitstop: 7,
      cancelInto: ['heavy', 'special'],
      lunge: 2,
      screenShake: 3,
      impact: 'light',
      sound: 'whiff-kick',
      hitSound: 'hit-light',
      animation: { row: 4, startup: [1, 2], active: [3], recovery: [3, 0] },
    },
    heavy: {
      id: 'dev-code-pillar',
      name: 'Кодовый столб',
      kind: 'heavy',
      damage: 110,
      startupFrames: 16,
      activeFrames: 8,
      recoveryFrames: 24,
      hitbox: { x: 270, y: 0, width: 140, height: 330 },
      knockback: { horizontalForce: 6, verticalForce: 15, duration: 30 },
      blockInteraction: 'guardBreak',
      blockstun: 18,
      hitstop: 10,
      cancelInto: ['special'],
      screenShake: 9,
      impact: 'heavy',
      sound: 'whiff-heavy',
      hitSound: 'hit-heavy',
      animation: {
        row: 8,
        startup: [1, 2],
        active: [3, 5],
        recovery: [5, 7],
        overlay: {
          row: 8,
          active: [4, 6],
          recovery: [8, 8],
          offsetX: 270,
          offsetY: 0,
          effect: { style: 'codePillar', splitX: 0, originY: 0, color: '#5ad8ff' },
        },
      },
    },
    airLight: {
      id: 'dev-air-jab',
      name: 'Воздушный джеб',
      kind: 'light',
      damage: 35,
      startupFrames: 5,
      activeFrames: 5,
      recoveryFrames: 8,
      hitbox: { x: 120, y: 160, width: 140, height: 110 },
      knockback: { horizontalForce: 3, verticalForce: 0, duration: 15 },
      blockInteraction: 'blockable',
      blockstun: 10,
      hitstop: 5,
      impact: 'light',
      sound: 'whiff-light',
      hitSound: 'hit-light',
      animation: { row: 3, startup: [1], active: [2], recovery: [2] },
    },
    airKick: {
      id: 'dev-air-kick',
      name: 'Удар в прыжке',
      kind: 'kick',
      damage: 55,
      startupFrames: 6,
      activeFrames: 7,
      recoveryFrames: 10,
      hitbox: { x: 130, y: 20, width: 170, height: 140 },
      knockback: { horizontalForce: 5, verticalForce: 0, duration: 18 },
      blockInteraction: 'blockable',
      blockstun: 13,
      hitstop: 7,
      screenShake: 3,
      impact: 'light',
      sound: 'whiff-kick',
      hitSound: 'hit-light',
      animation: { row: 4, startup: [2], active: [3], recovery: [3] },
    },
    airHeavy: {
      id: 'dev-air-heavy',
      name: 'Заряженный удар',
      kind: 'heavy',
      damage: 80,
      startupFrames: 10,
      activeFrames: 6,
      recoveryFrames: 14,
      hitbox: { x: 130, y: 100, width: 170, height: 150 },
      knockback: { horizontalForce: 6, verticalForce: 8, duration: 26 },
      blockInteraction: 'guardBreak',
      blockstun: 16,
      hitstop: 9,
      screenShake: 6,
      impact: 'heavy',
      sound: 'whiff-heavy',
      hitSound: 'hit-heavy',
      animation: { row: 8, startup: [1], active: [2], recovery: [3] },
    },
  },
  special: {
    id: 'dev-lightning',
    name: 'Молния деплоя',
    kind: 'special',
    damage: 170,
    energyCost: 50,
    startupFrames: 20,
    activeFrames: 18,
    recoveryFrames: 26,
    hitbox: { x: 470, y: 130, width: 760, height: 170 },
    knockback: { horizontalForce: 12, verticalForce: 12, duration: 38 },
    blockInteraction: 'guardBreak',
    blockstun: 20,
    hitstop: 14,
    energyGain: 0,
    screenShake: 14,
    impact: 'special',
    vfxColor: '#5ad8ff',
    sound: 'special-charge',
    hitSound: 'hit-special',
    animation: {
      row: 7,
      startup: [1, 2],
      active: [3, 4, 5],
      recovery: [5, 0],
      effect: { style: 'lightning', splitX: 105, originY: 130, color: '#5ad8ff' },
    },
  },
  combos: [
    {
      id: 'dev-hotfix',
      name: 'Хотфикс',
      sequence: ['light', 'light', 'kick'],
      maxGapFrames: 24,
      damageMultiplier: 1.5,
      knockback: { horizontalForce: 9, verticalForce: 9, duration: 30 },
      energyBonus: 10,
    },
    {
      id: 'dev-deploy-friday',
      name: 'Деплой в пятницу',
      sequence: ['light', 'kick', 'heavy'],
      maxGapFrames: 28,
      damageMultiplier: 1.3,
      energyBonus: 12,
    },
    {
      id: 'dev-merge-conflict',
      name: 'Мёрж-конфликт',
      sequence: ['kick', 'heavy', 'special'],
      maxGapFrames: 34,
      damageMultiplier: 1.2,
    },
  ],
}

export default developer
