import type { FighterDefinition } from '../types'

/**
 * fighter-2 «Продюсер» — source: figther-2/Продюсер - Борис Альхимович.png
 *
 * Atlas rows (row 0 = portraits):
 *  1 idle (0-1) + hit reaction (2-5)   7 money stream special
 *  2 walk                               8 taunt: wave, point, arms crossed
 *  3 jab                                9 victory
 *  4 kick                              10 dizzy
 *  5 jump                              11 KO
 *  6 laptop strike
 */
const producer: FighterDefinition = {
  id: 'producer',
  name: 'Продюсер',
  profile: {
    archetype: 'Финансовый магнат',
    speed: 'Средняя',
    health: 'Высокие',
  },
  assetDir: 'producer',
  portraits: { normal: 0, hurt: 3, ko: 4, select: 1 },
  spriteScale: 1.05,
  stats: {
    maxHp: 1550,
    walkSpeed: 5.4,
    backWalkSpeed: 4.4,
    jumpVelocity: 23,
    jumpForwardSpeed: 6.8,
    weight: 0.9,
  },
  hurtboxes: {
    standing: [
      { x: 0, y: 0, width: 150, height: 250 },
      { x: 0, y: 250, width: 160, height: 150 },
    ],
    airborne: [{ x: 0, y: 30, width: 160, height: 330 }],
    down: [{ x: 0, y: 0, width: 320, height: 90 }],
  },
  animations: {
    idle: { row: 1, frames: [0, 1], ticksPerFrame: 24, loop: true },
    walk: { row: 2, frames: [0, 1, 2, 3], ticksPerFrame: 8, loop: true },
    jumpSquat: { row: 5, frames: [0], ticksPerFrame: 4, loop: false },
    jump: { row: 5, frames: [1], ticksPerFrame: 6, loop: false },
    fall: { row: 5, frames: [2], ticksPerFrame: 6, loop: false },
    land: { row: 5, frames: [3], ticksPerFrame: 5, loop: false },
    hit: { row: 1, frames: [3, 3, 4], ticksPerFrame: 5, loop: false },
    block: { row: 8, frames: [4], ticksPerFrame: 10, loop: false },
    stun: { row: 10, frames: [1, 2, 3], ticksPerFrame: 9, loop: true },
    ko: { row: 11, frames: [1, 2, 3, 4, 5], ticksPerFrame: 7, loop: false },
    win: { row: 9, frames: [1, 2, 3, 4], ticksPerFrame: 12, loop: false },
    intro: { row: 8, frames: [1, 2, 3, 3], ticksPerFrame: 18, loop: false },
  },
  attacks: {
    light: {
      id: 'prod-jab',
      name: 'Джеб',
      kind: 'light',
      damage: 42,
      startupFrames: 6,
      activeFrames: 3,
      recoveryFrames: 10,
      hitbox: { x: 140, y: 250, width: 120, height: 70 },
      knockback: { horizontalForce: 3, verticalForce: 0, duration: 15 },
      blockInteraction: 'blockable',
      blockstun: 11,
      hitstop: 5,
      cancelInto: ['light', 'kick', 'heavy', 'special'],
      lunge: 1.2,
      impact: 'light',
      sound: 'whiff-light',
      hitSound: 'hit-light',
      animation: { row: 3, startup: [1], active: [2], recovery: [2, 0] },
    },
    kick: {
      id: 'prod-high-kick',
      name: 'Высокий удар',
      kind: 'kick',
      damage: 70,
      startupFrames: 9,
      activeFrames: 4,
      recoveryFrames: 16,
      hitbox: { x: 160, y: 170, width: 170, height: 130 },
      knockback: { horizontalForce: 6, verticalForce: 0, duration: 20 },
      blockInteraction: 'blockable',
      blockstun: 14,
      hitstop: 7,
      cancelInto: ['heavy', 'special'],
      lunge: 1.5,
      screenShake: 3,
      impact: 'light',
      sound: 'whiff-kick',
      hitSound: 'hit-light',
      animation: { row: 4, startup: [1, 2], active: [3, 4], recovery: [4, 0] },
    },
    heavy: {
      id: 'prod-laptop',
      name: 'Удар макбуком',
      kind: 'heavy',
      damage: 115,
      startupFrames: 15,
      activeFrames: 5,
      recoveryFrames: 22,
      hitbox: { x: 165, y: 150, width: 170, height: 190 },
      knockback: { horizontalForce: 10, verticalForce: 8, duration: 28 },
      blockInteraction: 'guardBreak',
      blockstun: 18,
      hitstop: 11,
      cancelInto: ['special'],
      lunge: 2.5,
      screenShake: 9,
      impact: 'heavy',
      sound: 'whiff-heavy',
      hitSound: 'hit-heavy',
      animation: { row: 6, startup: [1, 2], active: [3], recovery: [3, 0] },
    },
    airLight: {
      id: 'prod-air-jab',
      name: 'Воздушный джеб',
      kind: 'light',
      damage: 36,
      startupFrames: 5,
      activeFrames: 5,
      recoveryFrames: 8,
      hitbox: { x: 125, y: 160, width: 140, height: 110 },
      knockback: { horizontalForce: 3, verticalForce: 0, duration: 15 },
      blockInteraction: 'blockable',
      blockstun: 10,
      hitstop: 5,
      impact: 'light',
      sound: 'whiff-light',
      hitSound: 'hit-light',
      animation: { row: 3, startup: [1], active: [2], recovery: [2] },
    },
    airKick: {
      id: 'prod-air-kick',
      name: 'Удар в прыжке',
      kind: 'kick',
      damage: 58,
      startupFrames: 7,
      activeFrames: 7,
      recoveryFrames: 10,
      hitbox: { x: 140, y: 40, width: 170, height: 150 },
      knockback: { horizontalForce: 5, verticalForce: 0, duration: 18 },
      blockInteraction: 'blockable',
      blockstun: 13,
      hitstop: 7,
      screenShake: 3,
      impact: 'light',
      sound: 'whiff-kick',
      hitSound: 'hit-light',
      animation: { row: 4, startup: [2], active: [3], recovery: [3] },
    },
    airHeavy: {
      id: 'prod-air-laptop',
      name: 'Макбук сверху',
      kind: 'heavy',
      damage: 85,
      startupFrames: 11,
      activeFrames: 6,
      recoveryFrames: 14,
      hitbox: { x: 140, y: 60, width: 180, height: 200 },
      knockback: { horizontalForce: 7, verticalForce: 7, duration: 26 },
      blockInteraction: 'guardBreak',
      blockstun: 16,
      hitstop: 10,
      screenShake: 6,
      impact: 'heavy',
      sound: 'whiff-heavy',
      hitSound: 'hit-heavy',
      animation: { row: 6, startup: [2], active: [3], recovery: [3] },
    },
  },
  special: {
    id: 'prod-money-rain',
    name: 'Денежный поток',
    kind: 'special',
    damage: 165,
    energyCost: 50,
    startupFrames: 22,
    activeFrames: 20,
    recoveryFrames: 26,
    hitbox: { x: 470, y: 40, width: 760, height: 300 },
    knockback: { horizontalForce: 13, verticalForce: 10, duration: 38 },
    blockInteraction: 'guardBreak',
    blockstun: 20,
    hitstop: 14,
    energyGain: 0,
    screenShake: 14,
    impact: 'special',
    vfxColor: '#ffd23a',
    sound: 'special-charge',
    hitSound: 'hit-special',
    animation: {
      row: 7,
      startup: [1, 2],
      active: [3, 4, 5],
      recovery: [5, 0],
      effect: { style: 'money', splitX: 92, originY: 160, color: '#ffd23a' },
    },
  },
  combos: [
    {
      id: 'prod-investment',
      name: 'Инвестиция',
      sequence: ['light', 'light', 'kick'],
      maxGapFrames: 24,
      damageMultiplier: 1.5,
      knockback: { horizontalForce: 10, verticalForce: 8, duration: 30 },
      energyBonus: 10,
    },
    {
      id: 'prod-budget-cut',
      name: 'Бюджет урезан',
      sequence: ['kick', 'light', 'heavy'],
      maxGapFrames: 28,
      damageMultiplier: 1.35,
      energyBonus: 12,
    },
    {
      id: 'prod-deadline',
      name: 'Дедлайн',
      sequence: ['light', 'kick', 'special'],
      maxGapFrames: 34,
      damageMultiplier: 1.2,
    },
  ],
}

export default producer
